### ISSUE TITLE
Print array

### ISSUE THREAD

**Issue by http-request** [Yaha626/jsSandBox-yaha.github.io#1]
- [x] Improve current implementation (use only two for loops and one two dimension array)
- [x] Print array like that:
 1 0 0 0 2
 0 1 0 2 0
 0 0 3 0 0
 0 2 0 1 0
 2 0 0 0 1
- [x] If value n is odd, then print message 'N is odd, print without center value', then print array.

**Comment by Yaha626** [comment]
task from Slava is done here 
 https://github.com/Yaha626/jsSandBox-yaha.github.io/commit/72790c44aab18210671b0492af780efc1b3dd472
